name = "DistributedEnvironments"
uuid = "e6ba4677-9f99-4ce8-87c8-721beef79281"
authors = ["Albin Heimerson <albheim@hotmail.com>, Mattias Fält and Johan Ruuskanen"]
version = "0.3.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
MacroTools = "0.5"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
